" Settings and Key bindings
" =========================

" Vundle
source ~/.vim/bundles.vim

" Set to auto read when a file is changed from the outside
set autoread

" Remove 'Hit ENTER to continue' prompts
set shortmess=a

" set the leader key
let mapleader = "\<Space>"

" open a file
nnoremap <Leader>o :CtrlP<CR>

" make saving and quitting easier
command W w
command Q q
nmap <leader>w :w<cr>
nmap <leader>q :q<cr>

" save file as sudo (useful for handling the permission-denied error)
cnoremap sudow w !sudo tee % >/dev/null

" Reload VimRC
nmap <leader>r :so ~/.vimrc<CR>

" Turn on the WiLd menu for command completion
set wildmode=longest:list,full

" Treat long lines as break lines (useful when moving around in them)
map j gj
map k gk

" Join with line above (similar to J)
map K kJ

" move to beginning/end of line
nnoremap B ^
nnoremap E $

" Set colors
try
  colorscheme Tomorrow-Night-Eighties
catch
endtry
set background=dark
if &diff
  colorscheme evening
endif

" show command in bottom bar
set showcmd

" full color support
set term=screen-256color

" set encoding to utf-8
set encoding=utf-8

" enable anti-aliased fonts 
set anti

" set font
set guifont=Ubuntu\ Mono\ Bold\ 10

" Enable syntax highlighting
syntax enable

" shows the horizontal cursor line
set cursorline

" Use Unix as the standard file type
set ffs=unix,dos,mac

" always show the statusline
set laststatus=2

" load file type plugins + indentation
filetype plugin indent on 

" settings for showing grammatical errors
hi SpellBad cterm=underline
hi clear SpellBad
map \s :set spell! spelllang=en_us<CR>

" toggle paste
nmap \o :set paste!<CR>

" toggle column at 80 characters
nmap \c :call ToggleColorColumn()<CR>

" wrap lines
set wrap

" redraw only when we need to
set lazyredraw

" show invisible
set list listchars=tab:▸\ ,eol:¬,trail:•
nmap \l :set list!<CR>

" a tab is two spaces
set tabstop=2 shiftwidth=2

" backspace through everything in insert mode
set backspace=indent,eol,start

" respect hard tabs
set softtabstop=2

" convert tabs to spaces
set expandtab

" switch between hard tabs and spaces
nmap \t :call ToggleTab()<CR>

" Creating tabs and toggling
nmap L :tabn<CR>
nmap H :tabp<CR>
nmap <leader>t :tabnew<CR>

" enable folding
set foldenable

" open most folds by default
set foldlevelstart=10

" 10 nested fold max
set foldnestmax=10

" fold based on indent level
set foldmethod=indent

" highlight last inserted text
nnoremap gV `[v`]

" Turn off Swap Files
set noswapfile
set nobackup
set nowb 

" highlight search matches
set hlsearch

" incremental searching
set incsearch

" searches are case insensitive ...
set ignorecase

" ... unless they contain at least one capital letter
set smartcase

" This unsets the 'last search pattern' register by hitting return
nnoremap <CR> :noh<CR><CR>

inoremap <tab> <c-r>=InsertTabWrapper()<cr>
inoremap <s-tab> <c-n>

" switching splits
nnoremap <leader>j <C-W><C-J>
nnoremap <leader>k <C-W><C-K>
nnoremap <leader>l <C-W><C-L>
nnoremap <leader>h <C-W><C-H>

" resizing splits
nnoremap <leader>= <c-w>+
nnoremap <leader>- <c-w>-
nnoremap <leader>+ <c-w><
nnoremap <leader>_ <c-w>>

" new splits
nnoremap <leader><Bar> <c-w>v
nnoremap <leader>\ <c-w>s

" open new splits to right and bottom
set splitbelow
set splitright

" Enable mouse by default
nmap <leader>m :call ToggleMouse()<CR>
set mouse=a

" Show line numbers by default
set number

" Toggle showing line numbers on and off
nmap \n :setlocal number!<CR>

" turn off numbers plugin by default
let g:enable_numbers = 0

"" timeout
set ttimeout
set ttimeoutlen=0

" Fileetypes
autocmd! FileType mkd,markdown,md setlocal syn=off " Don't syntax highlight markdown because it's often wrong

" Recognize ClojureScript files as Clojure
au BufNewFile,BufRead *.cljs setf clojure

" Recognize Go files
au BufRead,BufNewFile *.go set filetype=go

" Syntax hightlighting for CSS, Less, and SCSS
autocmd BufRead,BufNewFile *.less,*.css set filetype=css omnifunc=csscomplete#CompleteCSS
au BufRead,BufNewFile *.scss set filetype=scss.css
autocmd FileType scss set iskeyword+=-

" Recognize Hanglebars files as html
autocmd BufRead,BufNewFile *.handlebars set filetype=html

" Reload current file
nmap <C-e> :e<CR>

" save session (restore with `vim -S`)
nnoremap <leader>s :mksession<CR>


" Functions
" =========

let g:togglecolumn_is_on = 0
function! ToggleColorColumn()
  if g:togglecolumn_is_on
    let g:togglecolumn_is_on = 0
    set colorcolumn=
  else
    let g:togglecolumn_is_on = 1
    set colorcolumn=80
  endif
endfunction

" allow toggling between local and default mode
function ToggleTab()
  if &expandtab
    set shiftwidth=2
    set softtabstop=0
    set noexpandtab
  else
    set shiftwidth=2
    set softtabstop=2
    set expandtab
  endif
endfunction

" Indent if we're at the beginning of a line. Else, do completion.
" Borrowed from @garybernhardt
function! InsertTabWrapper()
  let col = col('.') - 1
  if !col || getline('.')[col - 1] !~ '\k'
    return "\<tab>"
  else
    return "\<c-p>"
  endif
endfunction

" Toggle Mouse mode on and off
function! ToggleMouse()
  if &mouse == "a"
    set mouse=
    echo "Mouse Off"
  else
    set mouse=a
    echo "Mouse On"
  endif
endfunction

" Plugin Settings
" ===============

" Read in any plugin settings
if isdirectory(expand('$HOME/.vim/plugin-configs'))
  for f in split(glob('$HOME/.vim/plugin-configs/*.vim'), '\n')
    exe 'source' f
  endfor
endif

" Read in any marchine-specific vim settings
if isdirectory(expand('$HOME/.env'))
  for f in split(glob('$HOME/.env/*.vim'), '\n')
    exe 'source' f
  endfor
endif
