# Check for an interactive session
[ -z "$PS1" ] && return

#256 colors
export TERM="xterm-256color"

# set vi mode
set -o vi

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
HISTCONTROL=ignoredups:ignorespace

# append to the history file, don't overwrite it
shopt -s histappend

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# load functions and aliases
. ~/.aliases
. ~/.functions
. ~/.paths
. ~/.bindings
