# Disable software flow control (i.e. <ctrl>-s and <ctrl>-q)
stty -ixon

# Path oh-my-zsh configuration.
ZSH=$HOME/.zsh

# Set name of the theme to load.
ZSH_THEME="pure"
PURE_GIT_PULL=0

# Zsh settings
COMPLETION_WAITING_DOTS="true"
plugins=(vi-mode git z)

# Start Oh My Zsh
source $ZSH/oh-my-zsh.sh

# 10ms for key sequences (default is 400)
KEYTIMEOUT=1

# rm * without asking for confirmation
setopt rmstarsilent

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Set default editor
export EDITOR='vim'

# By default, zsh considers many characters part of a word (e.g., _ and -).
# # Narrow that down to allow easier skipping through words via M-f and M-b.
export WORDCHARS='*?[]~&;!$%^<>'

## re-bind zsh backwards search (gets unbound by vi-mode plugin)
bindkey '^[[A' up-line-or-search
bindkey '^[[B' down-line-or-search
bindkey '^[[3~' delete-char
bindkey '^R' history-incremental-search-backward
bindkey '^W' backward-kill-word    # vi-backward-kill-word
bindkey '^H' backward-delete-char  # vi-backward-delete-char
bindkey '^K' kill-line             # vi-kill-line
bindkey '^U' backward-kill-line
bindkey '^?' backward-delete-char  # vi-backward-delete-char
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line
bindkey '^F' forward-word
bindkey '^B' backward-word

# use v to launch edit command
autoload -Uz edit-command-line
zle -N edit-command-line
bindkey -M vicmd 'v' edit-command-line

# Load all of the config files in ~/oh-my-zsh that end in .zsh
# TIP: Add files you don't want in git to .gitignore
for config_file ($ZSH/lib/*.zsh); do
  source $config_file
done

# Load the theme
if [ ! "$ZSH_THEME" = ""  ]
  source "$ZSH/$ZSH_THEME.zsh-theme"
fi

# Load everything else
. $HOME/.paths
. $HOME/.aliases
. $HOME/.functions

# Load machine-specific env vars
if [ -d "$HOME/.env" ]; then
  for i in $HOME/.env/*.sh ; do source $i ; done
fi
