#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"

# import helper functions
. $di/functions

prompt_warning () {
  # warn user about overwriting files
  info "WARNING: This script will remove all current dotfile settings. \n"
  info "Would you like to continue? [Y/n]: "
  read cont
  printf "\n"
  if [ "$cont" = "n" ]; then
    echo "Exited."
    exit
  fi
}

install_dotfiles () {
  info 'Installing dotfiles'

  # sym link files
  . $di/symlink

  # setup gitconfig
  . $di/git

  # setup vim
  . $di/vim
  git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
  vim +BundleInstall +qall
}

install_programs () {
  info 'Installing Programs'

  # install programs
  . $di/programs
  
  # install packages
  . $di/packages
}


# let's do this!
prompt_warning
install_programs
install_dotfiles

success "All done!"
