#!/bin/bash

# functions for text formatting
info () {
  printf "  [ \033[00;34m..\033[0m ] $1"
}

user () {
  printf "\r  [ \033[0;33m?\033[0m ] $1 "
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link () {
  ln -s $1 $2
  success "linked $1 to $2"
}


# Default settings
backup_dir=$dd/backups/$(date +\%D)
backup=false
symlink=false
vundle_only=false

# Parse options
for i in "$@"
do
case $i in
    -s|--symlink)
    symlink=true
    shift
    ;;
    -b|--backup)
    backup=true
    shift
    ;;
    -d=*|--backup-dir=*)
    backup_dir="${i#*=}"
    shift
    ;;
    -v|--vundle)
    vundle_only=true
    shift
    ;;
    *)
            # unknown option
    ;;
esac
done

mkdir -p $backup_dir
