#!/bin/sh

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/dotfiles}
# dotfile install directory
di="$dd/install"
# import functions for text formatting
. $di/functions

setup_gitconfig () {
  if ! [ -f $dd/git/gitconfig.symlink ]
  then
    info 'setup gitconfig'

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" $dd/git/gitconfig.symlink.example > $dd/git/gitconfig.symlink

    link $dd/git/gitconfig.symlink ~/.gitconfig

    success 'gitconfig'
  fi
}

# run the config
setup_gitconfig
