#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"
# import settings and functions for text formatting
. $di/functions $@

remove_gitconfig () {
  unlink ~/.gitconfig
  if $backup; then
    mv ~/.gitconfig $backup_dir
  fi
}

setup_gitconfig () {
  info 'setup gitconfig'

  user ' - What is your github author name?'
  read -e git_authorname
  user ' - What is your github author email?'
  read -e git_authoremail

  sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" $dd/git/gitconfig.example > $dd/git/gitconfig

  if $symlink; then
    ln -s $dd/git/gitconfig ~/.gitconfig
  else
    cp $dd/git/gitconfig ~/.gitconfig
  fi

  success 'gitconfig'
}

remove_gitconfig
if ! $uninstall; then
  setup_gitconfig
fi
