#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"
# import settings and functions for text formatting
. $di/functions $@


prompt_warning () {
  # warn user about overwriting files
  info "WARNING: This script will replace all current dotfile settings. \n"
  info "         Old settings will be moved to '$backup_dir'. \n"
  info "Would you like to continue? [Y/n]: "
  read cont
  printf "\n"
  if [ "$cont" = "n" ]; then
    echo "Exited."
    exit
  fi
}


install_dotfiles () {
  info 'Installing dotfiles'

  # setup git
  . $di/git $@

  # setup shell
  . $di/shell $@

  # setup vim
  . $di/vim $@

  # setup tmux
  . $di/tmux $@
}

install_programs () {
  info 'Installing Programs \n'

  # install programs
  . $di/programs

  cp -r $dd/irssi ~/.irssi
  if [ "$os" = "o" ]
  then
    link $dd/osx/osx ~/.osx
    link $dd/osx/hushlogin ~/.hushlogin
    # Copy iterm2 settings
    cp $dd/osx/iterm/com.googlecode.iterm2.plist ~/Library/Preferences/
  fi
}


# let's do this!
prompt_warning
install_programs
install_dotfiles $@

success "All done!"
