#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"

# import helper functions
. $di/functions

  

pkgmgmt=true
while $pkgmgmt; do
  # check which os we're running
  info "Operating System [ a:arch, d:debian, r:redhat, o:osx ]: "
  read os
  printf "\n"

  # pick which package manager to use based on os
  case "$os" in
    "a")
      pkgmgmt="pacman -S"
      ;;
    "d")
      pkgmgmt="apt-get install"
      ;;
    "r")
      pkgmgmt="yum install"
      ;;
    "o")
      pkgmgmt="brew install"
      ;;
    *)
      echo "Please select a valid Operating System."
      ;;
  esac
done


# prepend sudo if not osx
[ $os != "o" ] && pkgmgmt="sudo $pkgmgmt"


# If osx, check if Homebrew is installed
if [ "$os" = "o" ]; then
  which -s brew
  if [[ $? != 0 ]] ; then
      # Install Homebrew
      info "Installing Homebrew"
      ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go)"
  fi
fi

# Update packages
info "Updating Packages"
$pkgmgmt update

# Install Zsh
info "Installing Zsh \n"
$pkgmgmt zsh
info "Setting zsh as default shell \n"
chsh -s /bin/zsh

# if osx, install things a little differently
if [ "$os" = "o" ]; then
  brew install readline sqlite gdbm --universal
  # install python with easy_install
  brew install python --universal --framework 
  # install pip
  sudo easy_install pip
  # Install wget with IRI support
  brew install wget --enable-iri
  # Install GNU core utilities (those that come with OS X are outdated)
  brew install coreutils
  echo "Don’t forget to add $(brew --prefix coreutils)/libexec/gnubin to \$PATH."
  # Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
  brew install findutils
  # Install Bash 4
  brew install bash
  brew install tree
  brew install lynx
  brew install node
  # Install native apps
  brew tap phinze/homebrew-cask
  brew install brew-cask

  installcask() {
    if brew cask info "${@}" | grep "Not installed" > /dev/null; then
      brew cask install "${@}"
    else
      echo "${@} is already installed."
    fi
  }

  installcask dropbox
  installcask google-drive
  installcask google-chrome
  installcask google-chrome-canary
  installcask iterm2
  installcask sublime-text
  installcask virtualbox
  installcask vlc
  installcask alfred
  # Link brew cask apps to Applications dir
  brew cask linkapps --appdir="/Applications"
  # Remove outdated versions from the cellar
  brew cleanup

  # setup mac defaults
  . ~/dotfiles/osx/osx-init
else
  $pkgmgmt python-pip vim
fi

# install tmux and curl
$pkgmgmt tmux curl
