#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"
# import settings and functions for text formatting
. $di/functions $@


shell_remove () {
  info 'removing shell configs'

  files=( .bashrc .zshrc .zsh .aliases .zsh_bindings .functions .paths )
  for i in "${files[@]}"
  do
    unlink ~/$i &>/dev/null
    if $backup; then
      mv ~/$i $backup_dir &>/dev/null
      success 'backed up $i'
    else
      rm ~/$i &>/dev/null
    fi
  done

  if $backup; then
    success 'removed and backed up shell configs'
  else
    success 'removed shell configs'
  fi
}


shell_setup () {
  info 'installing shell aliases, functions, and paths'

  if $symlink; then
    ln -s $dd/shell/aliases.sh ~/.aliases
    ln -s $dd/shell/functions.sh ~/.functions
    ln -s $dd/shell/paths.sh ~/.paths
  else
    cp $dd/shell/aliases.sh ~/.aliases
    cp $dd/shell/functions.sh ~/.functions
    cp $dd/shell/paths.sh ~/.paths
  fi

  success 'installed shell aliases, functions, and paths'
}

shell_setup_zsh () {
  info 'setting up zsh'

  if $symlink; then
    ln -s $dd/shell/zsh/zshrc ~/.zshrc
    ln -s $dd/shell/zsh ~/.zsh
  else
    cp $dd/shell/zsh/zshrc ~/.zshrc
    cp $dd/shell/zsh ~/.zsh
  fi

  success 'set up zsh'
}

shell_setup_bash () {
  info 'setting up bash'

  if $symlink; then
    ln -s $dd/shell/bash/bashrc ~/.bashrc
    ln -s $dd/shell/bash ~/.bash
  else
    cp $dd/shell/bash/bashrc ~/.bashrc
    cp -r $dd/shell/bash ~/.bash
  fi

  success 'set up bash'
}

# run the config
shell_remove
if ! $uninstall; then
  shell_setup
  shell_setup_zsh
  shell_setup_bash
fi
