#!/bin/sh

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/dotfiles}
# dotfile install directory
di="$dd/install"

# import helper functions
. $di/functions

# determine which os
if [ "$(uname -s)" == "Darwin" ]; then
  os="o"
else
  os="d"
fi

# Remove old files
info "Removing old files"
rm ~/.bashrc 
rm ~/.vimrc
rm -rf ~/.vim
rm ~/.gitconfig
rm ~/.zshrc
rm ~/.oh-my-zsh/themes/andrewk.zsh-theme
rm ~/.aliases
rm ~/.functions
rm ~/.bindings
rm ~/.paths
rm ~/.tmux.conf

if [ "$os" = "o" ]
then
  rm ~/.osx
  rm ~/.hushlogin
fi

# Sym link new files
info "Sym linking zsh files"
link $dd/zsh/zshrc ~/.zshrc
link $dd/zsh/aliases ~/.aliases
link $dd/zsh/functions ~/.functions
link $dd/zsh/paths ~/.paths
link $dd/zsh/bindings ~/.bindings
link $dd/zsh/themes/andrewk.zsh-theme ~/.oh-my-zsh/themes/andrewk.zsh-theme
link $dd/bash/bashrc ~/.bashrc


# Symbolic link files in dotfiles dir to home folder
link $dd/vim/vimrc ~/.vimrc
link $dd/vim/vim ~/.vim
link $dd/tmux/tmux.conf ~/.tmux.conf

# check if generated gitconfig exists. if it doesn't, generate it.
if ! [ -f $dd/git/gitconfig.symlink ]; then
  sh $di/git
fi
link $dd/git/gitconfig.symlink ~/.gitconfig

if [ "$os" = "o" ]
then
  link $dd/osx/osx ~/.osx
  link $dd/osx/hushlogin ~/.hushlogin
  # Copy iterm2 settings
  cp $dd/osx/iterm/com.googlecode.iterm2.plist ~/Library/Preferences/
fi
