#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"

# import helper functions
. $di/functions

# determine which os
if [ "$(uname -s)" == "Darwin" ]
then
  os="o"
else
  os="d"
fi

# Remove old files
info "Removing old files"
rm ~/.bashrc 
rm ~/.vimrc
rm -rf ~/.vim
rm ~/.zshrc
rm ~/.aliases
rm ~/.functions
rm ~/.bindings
rm ~/.paths
rm ~/.tmux.conf
rm ~/.osx
rm ~/.hushlogin
rm -rf ~/.irssi

# Sym link new files
info "Sym linking shell files"
link $dd/shell/zsh/zshrc.symlink ~/.zshrc
link $dd/shell/aliases.symlink ~/.aliases
link $dd/shell/functions.symlink ~/.functions
link $dd/shell/paths.symlink ~/.paths
link $dd/shell/bindings.symlink ~/.bindings
link $dd/shell/bash/bashrc.symlink ~/.bashrc

# Copy over .irssi configs, don't symlink them
cp -r $dd/irssi ~/.irssi

# Symbolic link files in dotfiles dir to home folder
link $dd/vim/vimrc ~/.vimrc
link $dd/vim ~/.vim
link $dd/tmux/tmux.conf.symlink ~/.tmux.conf

if [ "$os" = "o" ]
then
  link $dd/osx/osx.symlink ~/.osx
  link $dd/osx/hushlogin.symlink ~/.hushlogin
  # Copy iterm2 settings
  cp $dd/osx/iterm/com.googlecode.iterm2.plist ~/Library/Preferences/
fi
