#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"
# import settings and functions for text formatting
. $di/functions $@

remove_tmux () {
  info 'Backing up tmux settings.'

  unlink ~/.tmux.conf &>/dev/null
  if $backup; then
    mv ~/.tmux.conf $backup_dir &>/dev/null 
  fi

  success 'Backing up tmux settings.'
}

install_tmux () {
  info 'Installing tmux settings.'

  if $symlink; then
    ln -s $dd/tmux/tmux.conf ~/.tmux.conf
    ln -s $dd/tmux ~/.tmux
  else
    cp $dd/tmux/tmux.conf ~/.tmux.conf
    cp -r $dd/tmux ~/.tmux
  fi

  success 'Installing tmux settings.'
}

remove_tmux
if ! $uninstall; then
  install_tmux
fi
