#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"
# import settings and functions for text formatting
. $di/functions $@

files=( git shell vim tmux )
for i in "${files[@]}"
do
  . $di/$i --uninstall=true --backup=$backup --backup-dir=$backup_dir
done
