#!/bin/bash

# dotfile directory
dd=${DOTFILE_DIRECTORY:-~/.dotfiles}
# dotfile install directory
di="$dd/install"
# import functions for text formatting
. $di/functions $@

remove_vim () {
  info 'backup vim'

  unlink ~/.vimrc &>/dev/null
  mv ~/.vimrc $backup_dir &>/dev/null
  unlink ~/.vim &>/dev/null
  mv ~/.vim $backup_dir &>/dev/null

  success 'vim backup'
}

vim_setup () {
  info 'setup vim'

  if $symlink; then
    ln -s $dd/vim/vimrc ~/.vimrc
    ln -s $dd/vim ~/.vim
  else
    cp $dd/vim/vimrc ~/.vimrc
    cp $dd/vim ~/.vim
  fi

  success 'vim setup'
}

vim_vundle () {
  git clone https://github.com/gmarik/vundle.git $dd/vim/bundle/vundle
  vim +BundleInstall +qall
}

# run the config
if $vundle_only; then
  vim_vundle
else
  remove_vim
  if ! $uninstall; then
    vim_setup
    vim_vundle
  fi
fi
