#!/bin/sh

if [[ `tmux show-option -w | grep mode-mouse.*on` ]]; then
  toggle=off;
else 
  toggle=on; 
fi

tmux display-message "Mouse : $toggle";
tmux set-option -w mode-mouse $toggle &> /dev/null;
