# Determine OS
[[ `uname` == "Darwin" ]] && OS="osx" || OS="linux" # not checking for windows. screw that.

# Path oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
ZSH_THEME="andrewk"

# Zsh settings
COMPLETION_WAITING_DOTS="true"
plugins=(vi-mode git)

# Start Oh My Zsh
source $ZSH/oh-my-zsh.sh

# 10ms for key sequences (default is 400)
KEYTIMEOUT=1

# init z (https://github.com/rupa/z)
[ "$OS" = "osx" ] && . `brew --prefix`/etc/profile.d/z.sh

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "~/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# ruby
[ -e "/usr/local/opt/chruby/share/chruby/chruby.sh" ] && source /usr/local/opt/chruby/share/chruby/chruby.sh

# Load everything else
source ~/.paths
source ~/.aliases
source ~/.functions
source ~/.bindings
[ "$OS" = "osx" ] && source ~/.osx;

